@TicketBooking.API_HostAddress = http://localhost:5273

GET {{TicketBooking.API_HostAddress}}/bookings
Accept: application/json

###

GET {{TicketBooking.API_HostAddress}}/bookings/1
Accept: application/json

###

POST {{TicketBooking.API_HostAddress}}/bookings
Content-Type: application/json

{
  "customerName": "Mariza Duraku",
  "eventName": "Music Night Tirana",
  "eventType": "Concert",
  "eventDate": "2026-09-15",
  "seatNumber": "D10",
  "ticketQuantity": 2,
  "ticketPrice": 18.50,
  "status": "Booked"
}
